### ISSUE TITLE
Broken on 1.12

### ISSUE THREAD

**Issue by MegaNarwhal** [Rayzr522/JSONMessage#2]
Sending messages is broken on 1.12 because the constructor for PacketPlayOutChat has changed to use an enum constant instead of a byte.

**Comment by Rayzr522** [comment]
Alright, thanks for letting me know. I'll patch this up.

**Comment by Rayzr522** [comment]
Fixed in 0fb427f3d8dd9fe9c30024839a1f40ca6fc3b7c5, I tested it in 1.8 and 1.12.
