### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ItsNathanG** [Rayzr522/JSONMessage#3]
Hiya, this looks like an awesome library. I would love to use it in a plugin, but I'm hesitant due to no mention of a license anywhere.

Could you please include a LICENSE file somewhere or include what this is licensed under?

Thanks 👍

**Comment by Rayzr522** [comment]
Added in 097bcb6374ed4c8afd4977c5f0c6f22df8568c83.

I hope you enjoy :)

**Comment by ItsNathanG** [comment]
Great, thanks! 😄
