### ISSUE TITLE
Add 1.2.1 to the maven repo

### ISSUE THREAD

**Issue by extendedclip** [Rayzr522/JSONMessage#8]
Seems that I cant resolve the dependency when attempting to use 1.2.1. Can you compile / add the latest version to the repo?

**Comment by Rayzr522** [comment]
@extendedclip sorry, will do this soon, have been caught up with my job. before i do this, i need to optimize the reflection used in #7 (which I agreed to do outside the PR, since the author was unsure how to do it)

will let you know as soon as i've done that and published 1.2.1 for use! :)

**Comment by extendedclip** [comment]
Sweet man, I Really appreciate it! I’m going to wait to push an update to papi until then. Definitely appreciate your work dude!

**Comment by Rayzr522** [comment]
resolved by https://github.com/Rayzr522/maven-repo/commit/0cbbf3e0e541acdf2108cd76389a887b32605b19

let me know if you have any issues with it! should be significantly more optimized than the custom tweaked version that you guys were temporarily using in papi
